# Generated by Django 3.1.3 on 2022-06-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_answer',
            field=models.BooleanField(default=True),
        ),
    ]
