# Generated by Django 3.1.3 on 2022-06-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0013_remove_answer_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
